### ISSUE TITLE
Error: broken links (Edit page)

### ISSUE THREAD

**Issue by deining** [hugomods/site#148]
Navigate to https://hugomods.com/en/docs/shortcodes/bilibili/

At the bottom of the page, click on the `Edit` icon and select `Edit page`. 

https://github.com/hugomods/site/edit/%25!s%28%3cnil%3e%29/content/docs/shortcodes/bilibili/index.md

This link is broken:

```
404 - page not found
Cannot find a valid ref in 

%!s(<nil>)/content/docs/shortcodes/bilibili/index.md
```

There are many more pages that are affected, too.

**Comment by razonyang** [comment]
Thanks for your feedback.
