### ISSUE TITLE
太酷啦！厉害

### ISSUE THREAD

**Issue by g0fcn** [hugomods/site#883]
你好，很感谢你开发的这么牛的作品，让我知道hugo也可以这么帅
我也想中国国内可以正常使用
就目前来说打开速度上还可以，但是难免会有些静态资源国内访问有点难，请问可以自定义cdn嘛
因为你也知道中国很多cdn无法使用，他会很慢
emmm

然后你开发的admin真的让我看到了新世界，真的太强啦，但是有一点就是上传图片不能自定义链接，例如jsd这类 github cdn，国内访问github很慢很慢

感谢你

**Comment by razonyang** [comment]
感谢你对这些项目的喜爱。

> 请问可以自定义cdn嘛

具体是指什么 CDN 呢？印象模块都留有 `js_url` 之类的参数可供修改。

> 然后你开发的admin

如果你是指 Decap CMS，例子：https://hbstack.dev/admin/，并不是我开发的，我只是将其作为模块集成到 Hugo 了，目前模块功能不少，就是文档过旧，没啥时间写。

> 但是有一点就是上传图片不能自定义链接，例如jsd这类 github cdn，国内访问github很慢很慢

应该可以自定义链接的，可以提供详细的信息（如截图），以方便理解这个问题吗？

**Comment by g0fcn** [comment]
![IMG_20240218_195400.jpg](https://github.com/hugomods/site/assets/156695055/d2ec50b2-1203-4937-bbc6-824031d27df4)

大概是这样，可以自动切换托管的静态资源，emm国内这些cdn不知道啥时候就突然被墙了，导致整个网站无法访问，所以一般都切换cdn或者本地自己托管

**Comment by g0fcn** [comment]
decap cms已经很不错了，感觉很惊艳，emm从来没见过，我只见过用notion作为cms的https://g0f.notion.site/b3d5ebdd762d4f40976098cf40612239?v=9a3e1c31382e470bb2c46593be123b63&pvs=4
类似于这个，不过感觉你那个更直观一点，很棒

**Comment by razonyang** [comment]
> CDN ... 可以自动切换托管的静态资源

目前没有这样的统一设置，要修改的话，需要修改对应模块的参数。比如：
- https://hugomods.com/docs/content/mermaid/#configuration
- https://hugomods.com/docs/enhancement/aos/#site-parameters

**Comment by g0fcn** [comment]
好的谢谢，我刚刚用hugo，还没有研究就mods，待会研究研究

然后有个问题，不影响运行但是我想解决他不知道怎么做，您知道的话可以告知下我，谢谢![IMG_20240218_213217.jpg](https://github.com/hugomods/site/assets/156695055/75530d6c-4dd2-4723-abb0-b3ca175b71a5)

**Comment by razonyang** [comment]
第一个是因为图片不存在，建议全局搜索下104

第二个 archive 是因为某些文章没有设置日期

**Comment by g0fcn** [comment]
懂了谢谢
