### ISSUE TITLE
Can you do something with the "about"?

### ISSUE THREAD

**Issue by bep** [hugomods/site#93]
It currently says "Hugo Modules Official Site", which may lead people to lead that it's maintained by the Hugo project. Note that I think the site itself is very cool and useful to many, but it's _yours_ and not the _gohugoio_ GitHub org.

**Comment by razonyang** [comment]
Sorry about confusing this, modified, I modified the org description as well, please let me know if there is something misleading... 
![image](https://user-images.githubusercontent.com/17720932/231156385-7c74958d-7e15-463b-9ca2-87cdad0548d1.png)
